### ISSUE TITLE
Queue implementation currently uses a list under the hood. It should be modified to use a deque to make it efficient.

### ISSUE THREAD

**Issue by the-shank** [prakhar1989/Algorithms#42]
The `Queue` implementation, as it currently stands uses a list and then does a `self.items.insert(0, item)` to insert an item in the `Queue`. 
This is inefficient. A better approach is to modify `Queue` to use a `deque` under the hood, instead of a list for increased efficiency.
Please let me know if you agree with the above approach so that I can send a pull request with the appropriate changes.

**Comment by prakhar1989** [comment]
Completely agree. When I wrote that, I wasn't sure using a library ready queue (`deque`) was a good idea for implementing a queue. Feel free to send in a PR and I'll take a look. 👍

**Comment by the-shank** [comment]
Cool ! I will send the PR shortly.

**Comment by the-shank** [comment]
@prakhar1989 #43 PR sent

**Comment by prakhar1989** [comment]
Merged. Thanks for contributing 🍻
