### ISSUE TITLE
Bug in algorithm

### ISSUE THREAD

**Issue by zwhitchcox** [prakhar1989/Algorithms#7]
In the longest sequence code, the algorithms fails for this test

```seq = [5,0,1,2,3,4,5,6,7,8,9,10,11,12, 2, 8, 10, 3, 6, 9, 7]```

The output is ```(13, [0, 1, 2, 3, 4, 5, 6, 7])```, when there is clearly a longer sequence.

Just to let you know!

**Comment by prakhar1989** [comment]
Thanks for pointing this out. I'll try sending a fix soon. :+1:
